server:
  port: ${PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/seed
cors:
  allowed:
    api: /api/**
    method: '*'
security:
  patterns:
    ignoring:
      GET:
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html/**
      POST:
        - /api/users/signin
        - /api/users/signup
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      GET: [ ]
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
jwt:
  issuer: sfam
  client-secret:
  accessToken:
    header: atoken
    expiry-seconds: 30
  refreshToken:
    header: rtoken
    expiry-seconds: 120
