spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    url: jdbc:mysql://localhost:3306/${MYSQL_SCHEMA:team04}
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SHOW_SQL:true}

logging:
  level:
    com.kdt: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
