spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(nSSFICyQak/cBulXEeOEmlMHgdGIUy+L)
    password: ENC(JajXE4ahsIVgOBsyZ7BGrPQ3UZTJ0bIo)
    url: ENC(9d/4bHB1HmtQc/9cqFnK/mWXll5mHPVs1V1JBqNjyCTNZzj2CE62LTe7mWKNhCW1FK8Zh0JPGiFj8ICXRlCl65pco0f/r7TTLqJGYKeMDln1QkZRmttdcg==)
  jpa:
    show-sql: false
logging:
  level:
    org.hibernate.type.descriptor.sql: INFO
jwt:
  client-secret: ENC(vaOuavM8/QZzrntUSL/CLC3Q47399EsR)
encryptor:
  key: ${ENCRYPTOR_KEY}
