spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/seed
cors:
  allowed:
    api: /api/**
    method: '*'
security:
  patterns:
    ignoring:
      GET :
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html/**
    permit-all:
      GET:
        - /**
      POST:
        - /**
      DELETE:
        - /**
      PATCH:
        - /**
      PUT:
        - /**
jwt:
  issuer: sfam
  client-secret:
  accessToken:
    header: atoken
    expiry-seconds: 30
  refreshToken:
    header: rtoken
    expiry-seconds: 120