spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(nSSFICyQak/cBulXEeOEmlMHgdGIUy+L)
    password: ENC(JajXE4ahsIVgOBsyZ7BGrPQ3UZTJ0bIo)
    url: ENC(9d/4bHB1HmtQc/9cqFnK/mWXll5mHPVs1V1JBqNjyCTNZzj2CE62LTe7mWKNhCW1FK8Zh0JPGiFj8ICXRlCl65pco0f/r7TTLqJGYKeMDln1QkZRmttdcg==)
  jpa:
    show-sql: false
cors:
  allowed:
    origin:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - https://127.0.0.1:3000
      - https://localhost:3000
logging:
  level:
    org.hibernate.type.descriptor.sql: INFO
jwt:
  client-secret: ENC(vaOuavM8/QZzrntUSL/CLC3Q47399EsR)
encryptor:
  key: ${ENCRYPTOR_KEY}

cloud:
  aws:
    credentials:
      accessKey: ENC(hDiGnEdxfCONp6TSErL9SH4mAV/Z5sQEGS3ZBHxzv3E=)
      secretKey: ENC(lZHMD7ilan1QRzBtLwY+AYMCB1JrcVoqNZLuSeMgbL818TQ7QbLEPvRKG/qls5WjYY+0lP0CZgQ=)
    s3:
      bucket: ENC(YvPOdxAd97kzKfrsHEWhMafiIQufIo7b)
      url: ENC(Jd8ikLEflOap/jQTEMu+1XNBiVKqNzrug+Sek472b6SfG25fHEJ5nk1Q2afrDow2v7dxxhLquS/0nOsVeNWzZg==)
    region:
      static: ENC(WGH0CPvngxeIX0bpp8fLTnrAWMtglKek)
    stack:
      auto: false
